---
- hosts: control
  become: yes
  tasks:
  - name: install deps
    dnf:
      name:
        - python3-devel 
        - libffi-devel 
        - gcc 
        - openssl-devel 
        - python3-libselinux  
      state: present

  - name: install kolla-ansible
    pip:
      name: "{{ item }}"
      state: present
      virtualenv: "{{ playbook_dir}}/venv"
    with_items:
      - 'kolla-ansible'
      - 'ansible<2.10'

  - name: make dir /etc/kolla
    file:
      path: /etc/kolla
      state: directory
      owner: "{{ lookup('env','USER') }}"
      group: "{{ lookup('env','USER') }}"

  - name: cp globals
    copy:
      src: "{{ item }}"
      dest: /etc/kolla
    with_items: ["globals.yml", "venv/share/kolla-ansible/etc_examples/kolla/passwords.yml"]

