---
- hosts: control
  become: yes
  tasks:
  - name: install deps
    dnf:
      name:
        - python3-devel 
        - libffi-devel 
        - gcc 
        - openssl-devel 
        - python3-libselinux  
      state: present

  - name: install kolla-ansible
    pip:
      name: kolla-ansible
      state: present
      virtualenv: "{{ playbook_dir}}/venv"

  - name: make dir /etc/kolla
    file:
      path: /etc/kolla
      state: directory
      owner: "{{ lookup('env','USER') }}"
      group: "{{ lookup('env','USER') }}"

  - name: cp globals
    copy:
      src: globals.yml
      dest: /etc/kolla
