---
- hosts: control
  become: yes
  tasks:
  - name: install deps
    dnf:
      name:
        - python3-devel 
        - libffi-devel 
        - gcc 
        - openssl-devel 
        - python3-libselinux  
      state: present

  - name: install kolla-ansible
    pip:
      name: "{{ item }}"
      state: present
      virtualenv: "{{ playbook_dir}}/venv"
    with_items:
      - 'kolla-ansible'
      - 'ansible<2.10'

  - name: make dir /etc/kolla
    file:
      path: /etc/kolla
      state: directory
      owner: "{{ lookup('env','USER') }}"
      group: "{{ lookup('env','USER') }}"

  - name: cp globals
    copy:
      src: "{{ item }}"
      dest: /etc/kolla
    with_items: ["globals.yml", "venv/share/kolla-ansible/etc_examples/kolla/passwords.yml"]

  - name: filled passwords.yml
    command: "{{ playbook_dir}}/venv/bin/kolla-genpwd"

  - name: create device eth1
    net_interface:
      name: eth1
      state: present

  - name: create connection eth1
    command: nmcli connection add type dummy ifname eth1
#    nmcli:
#      conn_name: conn-eth1
#      ifname: eth1
#      type: ethernet
#      state: present
    tags: eth1
